name = "fluff"
version = "0.1.0"
description = "A Fortran linter and formatter - the 'ruff' for Fortran"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
license = "MIT"
copyright = "Copyright 2025, Christopher Albert"

[dependencies]
fortfront = { path = "../fortfront" }
stdlib = "*"

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive.git" }

[build]
auto-executables = true
auto-tests = true
auto-examples = true



[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"


